### ISSUE TITLE
BiliRoaming  1.1.3 在 Bilibili 5.45.2 失效

### ISSUE THREAD

**Issue by miyouzi** [meolunr/BiliRoaming#11]
<div>
<img src="https://user-images.githubusercontent.com/24269465/62103335-c46d1100-b2ce-11e9-9615-f123515cd9ce.png" width="30%" />

<img src="https://user-images.githubusercontent.com/24269465/62103340-c6cf6b00-b2ce-11e9-9101-3c1b26e8f9bd.png" width="30%" />

<img src="https://user-images.githubusercontent.com/24269465/62103345-c8992e80-b2ce-11e9-835e-39bd40ff2c29.png" width="30%" />
</div>

**Comment by meolunr** [comment]
请检查自定义主题色功能有没有生效？以及是否使用的是官方原版客户端？

**Comment by miyouzi** [comment]
原使用官方客户端的增量升级，后尝试卸载从官网下载重装，依然不能跨区。

自定义主题色功能有效。

**Comment by meolunr** [comment]
手机端使用 **MatLog** 这个应用，设置 filter 为 `BiliRoaming`，然后在客户端内尝试观看港澳台番剧，之后返回 MatLog 截取一下日志发我看下吧。

**Comment by miyouzi** [comment]
日志已上传
[2019-07-30-16-27-05.txt](https://github.com/iAcn/BiliRoaming/files/3445859/2019-07-30-16-27-05.txt)

**Comment by meolunr** [comment]
没有看到有用的信息。日志抓全了吗？应该从B站客户端一启动就开始抓的。

**Comment by miyouzi** [comment]
我再尝试了一次，log 在启动客户端之前就开始抓了，这次试了多个港澳台番剧，其中部分返回接口失败，但是 log 并没有相应的 error。
另外我的手机使用 5.45.0 客户端能够进入港澳台番剧, 但是无法播放。
[2019-07-30-16-46-18.txt](https://github.com/iAcn/BiliRoaming/files/3445950/2019-07-30-16-46-18.txt)

**Comment by meolunr** [comment]
还是没有。两种可能，一个是日志抓的不对，还有一个是太极没有正常加载起模块来。
正确的日志应该是类似这样的。
![snipaste_20190730_170209](https://user-images.githubusercontent.com/15158562/62116343-972f5b80-b2ec-11e9-8c97-9486280cb8ab.png)

**Comment by miyouzi** [comment]
不知道是不是ROM的问题，我的ROM是 flyme 7.3.0.0A。
用 adb 看 logcat，没有 D/BiliRoaming 开头的 log
![image](https://user-images.githubusercontent.com/24269465/62119542-6baf6f80-b2f2-11e9-92e1-a72dc235e15c.png)

**Comment by meolunr** [comment]
我更倾向于是觉得太极没有正常加载，只是如果没有正常加载的话自定义主题色也不会生效的，重新从太极里勾选下试试吧。

**Comment by miyouzi** [comment]
尝试了，同时取消了其他模块，情况没有发生变化，同样自定义主题有效，跨区无效

**Comment by meolunr** [comment]
试下 5.45.3 版本呢？

**Comment by miyouzi** [comment]
5.45.3 版本在哪里取得？

**Comment by meolunr** [comment]
我是从 APP 内部更新的

**Comment by miyouzi** [comment]
我这里 5.45.2 已提示最新

**Comment by wnark** [comment]
5.45.3可以正常使用吗

**Comment by miyouzi** [comment]
5.45.3及5.46.0在我这里解除地区限制功能均无法工作
