### ISSUE TITLE
可否增加回国功能

### ISSUE THREAD

**Issue by djytw** [meolunr/BiliRoaming#12]
首先感谢作者的插件 🤣
某些仅大陆版权的番剧在大陆以外的区域无法观看，是否可以增加对此类番剧的支持

**Comment by meolunr** [comment]
不好意思，回国功能需要大陆的服务器做中转，做的话也要等明年3月份台湾的服务器到期了。

**Comment by miyouzi** [comment]
@iAcn 有办法利用 BiliPlus 的 API 吗？类似油猴脚本 [解除B站区域限制](https://greasyfork.org/zh-CN/scripts/25718)

**Comment by djytw** [comment]
biliplus 的API是 www.biliplus.com/BPplayurl.php
我觉得可以加一个自定义中转服务器的配置

**Comment by meolunr** [comment]
@miyouzi @djytw BiliPlus 的 API 是没有办法用的，因为 BiliPlus 返回的数据是网页端格式的，客户端不能直接拿来用。自定义中转服务器的配置做起来不麻烦，只是加了真的有人用吗:pensive:

**Comment by djytw** [comment]
那个接口加上module=bangumi 参数就可以和http://api.bilibili.com/pgc/player/web/playurl 返回一样的数据

**Comment by meolunr** [comment]
实测是不行的，缺少几个客户端必需的参数。而且客户端官方接口是
`https://api.bilibili.com/pgc/player/`**api**`/playurl`
而不是 `https://api.bilibili.com/pgc/player/`**web**`/playurl`

**Comment by djytw** [comment]
你说的对，确实返回数据不太一样。如果能把参数对应过去就解决问题了
