### ISSUE TITLE
可不可以自己设置中转服务器

### ISSUE THREAD

**Issue by hanximeng** [meolunr/BiliRoaming#13]
我有一台闲置的香港小鸡，只做了一个小站，平时也没多大访问量，我希望可以用来搭一个中转服务器，最好是PHP，希望作者能开放相关代码。

**Comment by meolunr** [comment]
可以，不过做起来或许有点麻烦，我做了缓存，得用数据库。另外为什么要自己搭建中转服务器呢？客户端看视频的速度和中转服务器是没有关系的。

**Comment by hanximeng** [comment]
因为那台服务器我真的想不出拿来干嘛了（＃－.－） 放着生灰照样收费，不划算

**Comment by meolunr** [comment]
直接用反向代理吧。你一个人访问用不到缓存，我单独整理不带缓存的代码有点麻烦。你就直接做两个接口，一个番剧信息的，一个播放地址的。

**Comment by hanximeng** [comment]
好的
