### ISSUE TITLE
客户端版本5.45.2及5.46.0失效

### ISSUE THREAD

**Issue by djytw** [meolunr/BiliRoaming#15]
Season/Ep信息可以正常获取，播放数据失效，
原因是新版客户端的参数省略了module=bangumi 参数
getInputStream:https://api.bilibili.com/pgc/player/api/playurl?access_key=xxxx&appkey=xxx&build=5460500&buvid=xxx&cid=111120850&device=android&ep_id=276908&fnval=16&fnver=0&force_host=0&fourk=1&mobi_app=android&platform=android&qn=80&track_path=8&ts=1566139207&sign=xxx

**Comment by djytw** [comment]
实测改掉这个条件后可以正常使用
https://github.com/iAcn/BiliRoaming/blob/master/app/src/main/java/me/iacn/biliroaming/hooker/BangumiPlayUrlHook.java#L45

**Comment by missing233** [comment]
请求发布release

**Comment by wnark** [comment]
实测5.45.1,5.45.0也失效，症状表现为可以正常修改主题颜色，可以正常进入港澳台，就是显示加载失败，点击重新加载也没用，估计是相同原因。

**Comment by wnark** [comment]
> 实测改掉这个条件后可以正常使用
> https://github.com/iAcn/BiliRoaming/blob/master/app/src/main/java/me/iacn/biliroaming/hooker/BangumiPlayUrlHook.java#L45

求大佬打包文件，自己试了下完全搞不懂Android studio
自己尝试编译了个，无法修改主题无法看港澳台

**Comment by djytw** [comment]
@coldeve 太极的插件需要原作者签名。你可以试试原版xposed

**Comment by firegl99** [comment]
> @coldeve 太极的插件需要原作者签名。你可以试试原版xposed

我之前直接下载iAcn的apk配合太极可以直接使用啊，应该不用太极签名的。
另外我从你那边下载了代码，然后本地编译了，太极里面可以正常识别加载，但是还是看不了港澳台。
哔哩哔哩版本5.46.0

**Comment by firegl99** [comment]
@djytw 我之前直接下载iAcn的apk配合太极可以直接使用啊，应该不用太极签名的。
另外我从你那边下载了代码，然后本地编译了，太极里面可以正常识别加载，但是还是看不了港澳台。
哔哩哔哩版本5.46.0

**Comment by djytw** [comment]
@firegl99 原作者的签名=iAcn的签名

**Comment by wnark** [comment]
@djytw 由于是miui，目前装框架卡白米几率极大，所以只能用太极框架了。但我把自己编译的包发给用原版框架的人，他也不能用。。。可能是哪里出问题了
