### ISSUE TITLE
是否可以支持Tv版

### ISSUE THREAD

**Issue by Sato-Shio** [meolunr/BiliRoaming#17]

**Comment by meolunr** [comment]
电视上也没法用 Xposed 呀...

**Comment by ZerOri** [comment]
估计不太可能，只能路由器代理了，我记得PC端的脚本是检测到某些视频有地区限制就会从台湾服务器调取播放地址实现正常播放，理论上在路由器上应该也能做一个类似的插件或脚本来实现同样效果的
