### ISSUE TITLE
希望增加对谷歌商店版本的支持

### ISSUE THREAD

**Issue by ZerOri** [meolunr/BiliRoaming#19]
RT，这个插件真的很不错，省去了梯子的麻烦，但不支持谷歌商店的国际版哔哩哔哩有点遗憾，希望后续能兼容谷歌商店版本（v2.40+），感谢~

app地址：https://play.google.com/store/apps/details?id=com.bilibili.app.in&hl=zh

**Comment by Palpitace** [comment]
同求

**Comment by meolunr** [comment]
B站国际版代码老旧，有时间我看下吧。

**Comment by ZerOri** [comment]
> B站国际版代码老旧，有时间我看下吧。

感谢~

**Comment by yujincheng08** [comment]
play版本最近更新了，希望看看API是否有跟上普通版

**Comment by ZerOri** [comment]
> play版本最近更新了，希望看看API是否有跟上普通版

都已经是四个月前的事了 - -
