### ISSUE TITLE
或许,应该有一些使用向导

### ISSUE THREAD

**Issue by slothvips** [meolunr/BiliRoaming#2]

**Comment by slothvips** [comment]
安装之后,激活插件,客户端好像也没什么变化,搜索东京食尸鬼也没有出现在结果中

**Comment by meolunr** [comment]
不需要使用向导，确保插件已激活，然后像正常看番一样就可以了。
你搜索「东京食尸鬼」这几个关键字肯定是不行的，因为它叫「Tokyo Guru: re」。

**Comment by slothvips** [comment]
好的,谢谢让我了解
