### ISSUE TITLE
请问可以逆向解锁港澳台地区观看大陆区番剧吗

### ISSUE THREAD

**Issue by pochen448** [meolunr/BiliRoaming#25]
如题，麻烦大佬了。如果原本就可以，可能是因为用了酷友硬核翻新版的无效，不知道是不是硬核翻新导致的

**Comment by meolunr** [comment]
暂时是不可以的，只能解锁台湾地区的番剧观看。

**Comment by ZerOri** [comment]
这插件的原理是通过台湾服务器拉取播放地址绕过地区限制，如果想港澳台看大陆番剧还得另外弄大陆服务器。

**Comment by pochen448** [comment]
谢谢作者回答
