### ISSUE TITLE
关于5.57部分番剧入口失效的问题

### ISSUE THREAD

**Issue by yujincheng08** [meolunr/BiliRoaming#26]
新版5.57，在动态点击“哔哩哔哩番剧出差“的投稿或者在其视频投稿列表点击番剧会出现“视频不存在”的问题。在旧版中，点击之后会直接打开番剧页面并且使用`episode_id`获取信息。在5.57中，会先使用`aid`调用`app.bilibili.com/x/v2/view`接口，而这个接口在有区域限制的情况下会直接返回`404`。

目前的一个解决方案是利用`RetrofitResponseClass`的`constructors`的hook中的第一个参数。这个参数是`OkHttp3`的`Response`，其第一个成员是则是`OkHttp3`的`Request`，其中有一个方法`a() : OkHttp3.HttpURL`可以获取URL。判断URL是`view`接口并且返回值是`-404`的话，就可以利用URL中的query从代理服务器获取真实数据。获取成功之后，重构出一个`BiliVideoDetail`数据类替换`body.data`，并且把其成员`mBangumiInfo`的`mEpId`放到`lastSeasonInfo`，把URL中的`access_key`也放到`lastSeasonInfo`即可。
具体可以看看我的实现：
yujincheng08/BiliRoaming@61ef28c
由于这个需要后端代理服务器的配合，所以不能提PR了。

希望有帮助！

**Comment by meolunr** [comment]
好的，感谢反馈！但是我这边没看到有这个问题呢，如图。

从「哔哩哔哩番剧出差」的投稿列表中进入可以正常加载；关注后在「动态」中的时间线内没有出现投稿的视频；从「动态」上方的「我的番剧 · 追剧」中进入也没有问题。

只有在搜索框中搜索 _哔哩哔哩番剧出差_ 的搜索结果页面中的那一个最近投稿点进去才会出现「视频不见了哦」emmmm..

![Screenrecorder-2020-04-11-14-50-30-201](https://user-images.githubusercontent.com/15158562/79037987-55d7a580-7c08-11ea-9abc-91afdde11a07.gif)

**Comment by yujincheng08** [comment]
我这边是时间线是可以出现这个账号的（可能是我可能是我关注的人少），如图
![](https://user-images.githubusercontent.com/5022927/79038326-0a72c680-7c0b-11ea-886e-09c7fedd5b42.gif)

**Comment by meolunr** [comment]
可能是灰度测试，`app.bilibili.com/x/v2/view` 返回的很多字段都没有用上。
我这边清楚的看到哔哩哔哩番剧出差的最新投稿的一个是 13 小时前，但是在我的时间线内没有出现 (时间线内 5 小时前和 14 小时前的都有)。无法测试了..

**Comment by yujincheng08** [comment]
可能是灰度了。那就等正式上线再看也不迟。Issue就关了。
（用`view`这个接口太蠢了，要跳转一次，`playurl`也获取两次，不知道产品经理怎么想的

**Comment by yujincheng08** [comment]
找到原因了。这个可能是这个版本（5.57）的一个bug。原来的`com.bilibili.bplus.followingcard.api.entity.cardBean.VideoCard`的`getUrl`会优先返回`redirect_url`。5.57.0改了这个逻辑，把`getUrl`变成两个函数`getJumpUrl`和`getCommentJumpUrl`。但是这两个函数均忽略了`redirectUrl`，所以不能直接跳转到番剧页面。
所以修复应该挺简单的，就是让这两个函数优先返回一下`redirectUrl`就好了。具体可以参照我的commit（需要的话我可以提个pr）：
yujincheng08/BiliRoaming@1fe18d4

所以这个issue并不是灰度测试的问题，而是真实存在的。issue我就重开了。
另外，搜索点击最新投稿与这个无关，旧版就有了，算是小瑕疵吧，无伤大雅。

**Comment by meolunr** [comment]
看到了，我这边今天时间线内也出现哔哩哔哩番剧出差的投稿了，确实有这个问题。
感谢帮助！有时间的话你就发个 PR 吧，我合进去。
