### ISSUE TITLE
重新激活edxposed会导致所有hook功能失效

### ISSUE THREAD

**Issue by kooritea** [meolunr/BiliRoaming#29]
更新ROM后重新刷入magisk，即 重新激活edxposed
其他模块正常，哔哩漫游显示已启用，提示模块运行信息的toast正常弹出，模块日志有输出`start hook Comment`，但是实际上功能没有生效

尝试关闭模块，重启，激活模块，重启 -> 依然是只有toast弹出
尝试重装模块 -> 依然是只有toast弹出
尝试删除`/data/user/0/tv.danmaku.bili/cache/hookinfo.dat`  -> 依然是只有toast弹出

卸载b站app重装 -> 功能生效

**Comment by kooritea** [comment]
才发现这个仓库不维护了。。

**Comment by meolunr** [comment]
抱歉，你貌似使用的不是我原始代码的版本，因为我没有做 toast 提示。
我的版本暂时不会更新了，请联系其他 fork 分支的维护者。

**Comment by kooritea** [comment]
是的，不好意思打扰了。。
我搜仓库没有确认作者
