### ISSUE TITLE
提示：接口返回失败

### ISSUE THREAD

**Issue by YazawaNiko7** [meolunr/BiliRoaming#3]
5.40.0的B站配合1.0.7版哔哩漫游，使用太极启用哔哩漫游，看东京喰种RE（仅港澳台）提示：接口返回失败。

**Comment by meolunr** [comment]
刚测试了一下，我这儿是可以的。
请告诉我更加详细的信息以确认这个问题（太极是否支持，或者log等）

**Comment by YazawaNiko7** [comment]
@iAcn 太极已经支持了...log我不知道怎么找

**Comment by meolunr** [comment]
电脑端可以使用 adb 命令 `adb logcat BiliRoaming:D`。
手机端可以使用 **MatLog** 这个应用，然后 Filter 设置 Log Tag 为 `BiliRoaming`。

另外，是只有「Tokyo Guru: re」不能看吗？还是其他的都不行？你是在国内还是海外？

**Comment by YazawaNiko7** [comment]
@iAcn 只有这个，其他的正常

这是log
04-16 23:55:56.175 D/BiliRoaming(22331): SeasonInformation: seasonId = null
04-16 23:55:56.575 D/BiliRoaming(22331): SeasonResponse: code = -404, result = null

好像unnatural也不行

**Comment by meolunr** [comment]
不好意思，本地无法复现该问题，爱莫能助。
