### ISSUE TITLE
在太极上面优化app后模块失效

### ISSUE THREAD

**Issue by MMMXDyyy** [meolunr/BiliRoaming#30]
模块版本1.2.9  太极版本6.4.0 哔哩哔哩版本6.5.0  如题 优化app后模块全部功能失效

**Comment by TsXor** [comment]
那你就长按选取消优化啊
微信用微X模块时优化后也会出一些奇怪的bug，比如有时无限加载，被邀请加群时点加入的按钮会闪退之类的
太极里的APP优不优化都差不多，至少我的体验是这样
我的理解是：太极的“优化”是为了模块运行更好，而非优化运行速度，既然优化了反而用不了就取消优化算了（当然，优化不出问题建议仍保持优化状态）

*看了眼时间发现是好几个月前的，但一般来说模块如果不为太极专门优化（或太极适配引擎特殊照顾），优化出bug的问题是不会停下来的

**Comment by meolunr** [comment]
在太极上「优化」这个步骤并不是必须的。如果本身模块可以使用且功能正常，那么并不建议再去优化。
我暂时没有无极，不能使用 debug 在太极上运行调试，所以无法测试，抱歉。
