### ISSUE TITLE
太极不支持1.08，可否申请下太极对1.08的支持？

### ISSUE THREAD

**Issue by memphise** [meolunr/BiliRoaming#6]
使用太极加载1.08版本提示的时候，提示只支持1.00，1.02 ，1.06 ， 1.07，测试1.08加载后未生效。

**Comment by meolunr** [comment]
太极不支持需要给太极发 issue。

**Comment by memphise** [comment]
> 太极不支持需要给太极发 issue。

好的，我去提交一下iusse吧，提前和你打招呼一下征求同意，之前以为是需要作者本人去发的。
