### ISSUE TITLE
BiliRoaming 1.0.8 失效

### ISSUE THREAD

**Issue by memphise** [meolunr/BiliRoaming#7]
bilibili客户端版本：5.39.0
biliRoaming版本：1.0.8
复现步骤视频：https://www.lanzous.com/i4826yj

报错日志：
error log
>
Search "BiliRoaming" (27 hits in 1 file)
  E:\Program_Files\androidkiller\bin\adb\log.txt (27 hits)
	Line 3370: 05-19 21:27:14.254 I/ExposedBridge( 2876): Loading modules from /data/app/me.iacn.biliroaming-VvbHBPxeK_v7AVg-MMhGSg==/base.apk for process: tv.danmaku.bili
	Line 3372: 05-19 21:27:14.258 I/ExposedBridge( 2876):   Loading class me.iacn.biliroaming.XposedInit
	Line 3465: 05-19 21:27:14.664 D/BiliRoaming( 2876): BiliBili process launched: enableMainFunc = true
	Line 3466: 05-19 21:27:14.664 D/BiliRoaming( 2876): Reading hook info: /data/user/0/tv.danmaku.bili/cache/hookinfo.dat
	Line 3467: 05-19 21:27:14.668 D/BiliRoaming( 2876): Read hook info completed: cost 4 ms
	Line 3468: 05-19 21:27:14.668 D/BiliRoaming( 2876): Check hook info completed: needUpdate = false
	Line 3469: 05-19 21:27:14.668 D/BiliRoaming( 2876): startHook: BangumiSeason
	Line 3710: 05-19 21:27:15.227 I/ExposedBridge( 3006): Loading modules from /data/app/me.iacn.biliroaming-VvbHBPxeK_v7AVg-MMhGSg==/base.apk for process: tv.danmaku.bili:push
	Line 3728: 05-19 21:27:15.230 I/ExposedBridge( 3006):   Loading class me.iacn.biliroaming.XposedInit
	Line 3853: 05-19 21:27:15.496 I/ExposedBridge( 3034): Loading modules from /data/app/me.iacn.biliroaming-VvbHBPxeK_v7AVg-MMhGSg==/base.apk for process: tv.danmaku.bili:ijkservice
	Line 3855: 05-19 21:27:15.501 I/ExposedBridge( 3034):   Loading class me.iacn.biliroaming.XposedInit
	Line 3919: 05-19 21:27:15.737 I/ExposedBridge( 3152): Loading modules from /data/app/me.iacn.biliroaming-VvbHBPxeK_v7AVg-MMhGSg==/base.apk for process: tv.danmaku.bili:stats
	Line 3922: 05-19 21:27:15.741 I/ExposedBridge( 3152):   Loading class me.iacn.biliroaming.XposedInit
	Line 3999: 05-19 21:27:15.999 I/ExposedBridge( 3300): Loading modules from /data/app/me.iacn.biliroaming-VvbHBPxeK_v7AVg-MMhGSg==/base.apk for process: tv.danmaku.bili:download
	Line 4001: 05-19 21:27:16.003 I/ExposedBridge( 3300):   Loading class me.iacn.biliroaming.XposedInit
	Line 4134: 05-19 21:27:16.414 D/BiliRoaming( 3300): startHook: BangumiPlayUrl
	Line 4567: 05-19 21:27:21.512 I/ExposedBridge( 3650): Loading modules from /data/app/me.iacn.biliroaming-VvbHBPxeK_v7AVg-MMhGSg==/base.apk for process: tv.danmaku.bili:web
	Line 4569: 05-19 21:27:21.515 I/ExposedBridge( 3650):   Loading class me.iacn.biliroaming.XposedInit
	Line 4854: 05-19 21:27:24.511 D/BiliRoaming( 2876): SeasonInformation: seasonId = 26963
	Line 4869: 05-19 21:27:24.673 D/BiliRoaming( 2876): SeasonResponse: code = 0, result = com.bilibili.bangumi.api.uniform.BangumiUniformSeason@53acef
	Line 4870: 05-19 21:27:24.673 D/BiliRoaming( 2876): Limited Bangumi: seasonInfo = {access_key=73133b1d13a679befcf7b58094212a51, type=0, season_id=26963}
	Line 5022: 05-19 21:27:26.382 D/BiliRoaming( 2876): SeasonInformation: seasonId = 24629
	Line 5023: 05-19 21:27:26.641 D/BiliRoaming( 2876): SeasonResponse: code = -404, result = null
	Line 5024: 05-19 21:27:26.642 D/BiliRoaming( 2876): Limited Bangumi: seasonInfo = {access_key=73133b1d13a679befcf7b58094212a51, type=0, season_id=24629}
	Line 5500: 05-19 21:27:30.498 D/BiliRoaming( 2876): SeasonInformation: seasonId = 24629
	Line 5520: 05-19 21:27:30.628 D/BiliRoaming( 2876): SeasonResponse: code = -404, result = null
	Line 5521: 05-19 21:27:30.628 D/BiliRoaming( 2876): Limited Bangumi: seasonInfo = {access_key=73133b1d13a679befcf7b58094212a51, type=0, season_id=24629}

**Comment by meolunr** [comment]
收到，已查明原因。最近非常忙，过段时间修复。
