### ISSUE TITLE
可否同时支持谷歌版哔哩哔哩？

### ISSUE THREAD

**Issue by TinkMingKing** [meolunr/BiliRoaming#9]
如题

**Comment by meolunr** [comment]
不好意思，国际版上的功能落后国内好几个版本，而且接口也不一样，不打算兼容。

**Comment by ZerOri** [comment]
> 不好意思，国际版上的功能落后国内好几个版本，而且接口也不一样，不打算兼容。

那有没有可能再做一版国际版哔哩哔哩的？
